spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: 'https://github.com/ednaldofranco/microservice-repo-1'
server:
  port: 8888


